### ISSUE TITLE
Problem: Pull requests may go unnoticed

### ISSUE THREAD

**Issue by weex** [OpenHospitalityNetwork/fedi-trustroots#11]
To support smooth development, and per 2.4.15 of https://rfc.zeromq.org/spec/42/, Maintainers should merge correct pull requests rapidly, yet unless a maintainer is watching (being notified) for pull requests, they won't know about it, even if they are in the Matrix channel.

Potential solution: Setup a github action to [send a message to the chat](https://github.com/marketplace/actions/matrix-message) when anything pull request-related happens. This requires an access key for the channel be available to the github action.

**Comment by aschrijver** [comment]
It is weird that Github does not notify organization repo maintainers when PR's occur (not in the notification window, nor by email). I contacted support for that in the past. There may also be a GH Action to inform maintainers more directly (didn't check).

**Comment by weex** [comment]
Just opened a pull request and it failed to notify.

**Comment by mariha** [comment]
After [GitHub docs about encrypted secrets](https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow):

> Note: With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

Looks like that GH Action won't work with C4 flow based on forks.

@weex one thing that you can do is to _Watch_ the repo, as you do for the one with webpage, then you'll get emails for all the activities.

Some other ideas:
1. when creating a pr ask everyone to assign or mention you or other selected people
1. add CODEOWNERS with maintainers team - everyone will be requested for review and email-notified
1. add selected people (you) to CODEOWNERS
1. set notifications with some other CI (quick search: Travis can notify matrix, CircleCi can notify irc or slack which can be bridged to matrix...)

I'd do either 2 or 4. As for me e-mail is good enough (in terms of timely feedback), we could consider auto-merge in the future in some cases, ex. when there was executable specification and all tests passed.

**Comment by weex** [comment]
I've set to watch for pull-requests and email is probably fine for me as well. I'm confused as to how PR notifications to Matrix work for any repo since pull requests are always created from a fork. I suppose OpenHospitalityNetwork/fedi-trustroots also being a fork can complicate? In any case, I'm satisfied with GH watching. Feel free to close.

**Comment by chagai95** [comment]
A workaround could be to set a dedicated email for this and forward all three inbox to the matrix chat, should be easy to setup

**Comment by mariha** [comment]
> I'm confused as to how PR notifications to Matrix work for any repo since pull requests are always created from a fork.

@weex it's possible to create PR from a branch. Many projects develop on public branches actually, rather then forks. It's more lightweight - doesn't make distinction of ownership that explicit though.

@chagai95 at this point I feel like effort/benefits is not worth it, feel free to do it if you'd like though!

**Comment by weex** [comment]
Currently, this leaves a red X on any PRs so it would be an improvement to remove the current integration.
