### ISSUE TITLE
Problem: trustroots.org and derivatives are hard-coded in many places

### ISSUE THREAD

**Issue by weex** [OpenHospitalityNetwork/fedi-trustroots#12]
trustroots.org, sub-domains like grafana.trustroots.org and derivatives like trustroots_org are hard-coded in javascript, html, scripts, txt files and other places that would interfere with operation of a federated instance.

**Comment by mariha** [comment]
I set up email forwarding (to me...) for `*@openhospitality.network`, we can use `whitelabeled@openhospitality.network` or  `fairtravellers@openhospitality.network` ;) or something similar until we have a name and domain for the bicycle touring community.

**Comment by weex** [comment]
Closing this since we have #52 and #56
