### ISSUE TITLE
Server.md points to old Passenger install document location

### ISSUE THREAD

**Issue by weex** [OpenHospitalityNetwork/fedi-trustroots#13]
This may not be relevant if this isn't the way to install a production server, but wanted to capture that the [Passenger installation link](https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#install_on_debian_ubuntu) in https://github.com/OpenHospitalityNetwork/fedi-trustroots/blob/master/docs/Server.md says the documentation moved.

The new location is https://www.phusionpassenger.com/library/install/nginx/apt_repo/

We can close this if, we don't plan to support this kind of manual installation.

**Comment by mariha** [comment]
Would be nice to fix it in the upstream repo.
