### ISSUE TITLE
whitelabel it

### ISSUE THREAD

**Issue by weex** [OpenHospitalityNetwork/fedi-trustroots#42]
Please see #16 (I clicked convert to issue an not sure how to undo that)

**Comment by mariha** [comment]
Thanks for pointing it out! I've added #16 to the roadmap so will close this one.

> (I clicked convert to issue an not sure how to undo that)

you can edit issues from the menu under three dots on the top right corner of the pad, but I guess you know that because this one is edited ;) either way, I am closing it.
